# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "aqua"

# Site Settings
locale: "en-US"
title: "GEOPOL"
title_separator: "-"
subtitle: "Geopolitics, Defense & World Affairs"
description: "In-depth insights, current affairs, and strategic analysis."

# URL & Path Settings
url: "https://daksh-bordiya.github.io"
baseurl: "/geopol"
repository: "daksh-bordiya/geopol"
permalink: /:categories/:title/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Exclude unnecessary files
exclude:
  - CHANGELOG.md
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
