# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "aqua"

# Site Settings
locale: "en-US"
title: "GEOPOL"
title_separator: "-"
subtitle: "Geopolitics, Defense & World Affairs"
description: "In-depth insights, current affairs, and strategic analysis."

# URL & Path Settings
url: "https://daksh-bordiya.github.io"
baseurl: "/geopol"
repository: "daksh-bordiya/geopol"
logo: "/assets/images/logo.png"

# Reading Settings
words_per_minute: 200
enable_copy_code_button: true

# Conversion & Formatting
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
future: true

# Custom Collections
collections:
  current_affairs:
    output: true
    permalink: /current-affairs/:slug/
  stories:
    output: true
    permalink: /stories/:slug/

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Exclude unnecessary files
exclude:
  - CHANGELOG.md
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
